#!/bin/bash

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  HERMES INIT
#  Scaffolds cc-forge structure for a new project
#  Run from your project root AFTER cloning/creating
#  Usage: bash /path/to/hermes-sdlc/scripts/hermes-init.sh
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

set -e

HERMES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_DIR="$(pwd)"
PROJECT_NAME="$(basename "$PROJECT_DIR")"
DATE="$(date +%Y-%m-%d)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  HERMES INIT  ·  $PROJECT_NAME"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Check prerequisites ──────────────────────────
echo "▸ Checking prerequisites..."

if ! command -v claude &> /dev/null; then
  echo "  ✗ Claude Code not found"
  echo "    Install: https://claude.ai/code"
  exit 1
fi

if ! command -v git &> /dev/null; then
  echo "  ✗ Git not found"
  exit 1
fi

echo "  ✓ All prerequisites met"
echo ""

# ── Check if already initialized ────────────────
if [ -f ".cc-forge/state.json" ]; then
  echo "  ⚠ This project already has cc-forge initialized."
  echo "  Run '/hermes adopt' in Claude Code instead."
  exit 1
fi

# ── Create cc-forge directory ────────────────────
echo "▸ Creating cc-forge structure..."

mkdir -p .cc-forge
mkdir -p .github/workflows
mkdir -p .claude/commands

# ── Write state file ─────────────────────────────
cat > .cc-forge/state.json << EOF
{
  "project": "$PROJECT_NAME",
  "initialized_at": "$DATE",
  "mode": "greenfield",
  "current_stage": 1,
  "stage_name": "IDEA",
  "stack": {
    "language": "TypeScript",
    "framework": "Next.js 14",
    "database": "PostgreSQL via Prisma",
    "auth": "Clerk",
    "billing": "Stripe",
    "hosting": "Railway"
  },
  "gates_passed": [],
  "personas_run": []
}
EOF

echo "  ✓ .cc-forge/state.json"

# ── Copy Hermes commands ─────────────────────────
echo "▸ Installing Hermes commands..."

for cmd_file in "$HERMES_DIR"/hermes/commands/*.md; do
  cmd_name=$(basename "$cmd_file")
  cp "$cmd_file" .claude/commands/"$cmd_name"
  echo "  ✓ .claude/commands/$cmd_name"
done

# ── Write CLAUDE.md stub ─────────────────────────
if [ ! -f "CLAUDE.md" ]; then
  cat > CLAUDE.md << EOF
# $PROJECT_NAME

## What this is
[One sentence: what it does and who it's for]

## Stack
- Runtime: Node 20 / Next.js 14
- Language: TypeScript (strict)
- Database: PostgreSQL via Prisma
- Auth: Clerk
- Billing: Stripe
- Hosting: Railway

## Commands
- Dev:           \`npm run dev\`
- Build:         \`npm run build\`
- Test:          \`npm test\`
- DB migrate:    \`npx prisma migrate dev\`
- DB studio:     \`npx prisma studio\`
- Type check:    \`npx tsc --noEmit\`

## Conventions
- Files: kebab-case
- Components: PascalCase
- Hooks: use* prefix
- API routes: /api/[resource]/route.ts
- Never use \`any\` — use \`unknown\` + type guards
- Controllers call services. Services call DB. Never bypass.

## Current stage
cc-forge stage: 01 IDEA
EOF
  echo "  ✓ CLAUDE.md"
else
  echo "  · CLAUDE.md already exists — skipping"
fi

# ── Write PRD stub ───────────────────────────────
if [ ! -f "PRD.md" ]; then
  cat > PRD.md << EOF
# Product Requirements Document
> Project: $PROJECT_NAME
> Created: $DATE | Status: DRAFT
>
> Generated by Hermes. Run '/hermes init' in Claude Code to
> complete the onboarding interview and flesh this out.

## Problem statement
[What problem does this solve? Who has it?]

## Target user
[Who is the primary user?]

## Core use cases
1. [Primary use case]
2. [Secondary use case]

## MVP features
- [ ] [Feature]

## Out of scope (MVP)
- [Thing not building yet]

## Success metrics
- [How you'll know it's working]

## Open questions
- [ ] [Question to answer before building]
EOF
  echo "  ✓ PRD.md"
else
  echo "  · PRD.md already exists — skipping"
fi

# ── Write .env.example ───────────────────────────
if [ ! -f ".env.example" ]; then
  cat > .env.example << EOF
# Database
DATABASE_URL=

# Clerk Authentication
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=
CLERK_WEBHOOK_SECRET=
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard

# Stripe Billing
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
STRIPE_PRICE_ID_PRO_MONTHLY=

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Monitoring (add after deploy)
SENTRY_DSN=
NEXT_PUBLIC_SENTRY_DSN=
EOF
  echo "  ✓ .env.example"
else
  echo "  · .env.example already exists — skipping"
fi

# ── Write GitHub Actions ─────────────────────────
echo "▸ Writing GitHub Actions..."

cat > .github/workflows/doc-sync.yml << 'EOF'
name: Doc Sync

on:
  pull_request:
    types: [closed]
    paths:
      - "src/**"
      - "app/**"
      - "api/**"
      - "prisma/**"

jobs:
  sync-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            A PR was just merged. Review the changes and update any
            documentation that is now out of date — README.md, CHANGELOG.md,
            ARCHITECTURE.md, API.md, and any docs/ files.
            Commit updates directly to main with message:
            "docs: sync after PR #${{ github.event.pull_request.number }}"
EOF

cat > .github/workflows/claude-review.yml << 'EOF'
name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
EOF

echo "  ✓ .github/workflows/doc-sync.yml"
echo "  ✓ .github/workflows/claude-review.yml"

# ── Write .gitignore additions ───────────────────
if [ -f ".gitignore" ]; then
  if ! grep -q ".cc-forge/state.json" .gitignore; then
    echo "" >> .gitignore
    echo "# cc-forge" >> .gitignore
    echo ".cc-forge/state.json" >> .gitignore
    echo "  ✓ .gitignore updated"
  fi
else
  cat > .gitignore << 'EOF'
# Dependencies
node_modules/

# Next.js
.next/
out/

# Environment
.env
.env.local
.env.*.local

# cc-forge
.cc-forge/state.json

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*
EOF
  echo "  ✓ .gitignore created"
fi

# ── Initialize git if needed ─────────────────────
if [ ! -d ".git" ]; then
  git init
  git add .
  git commit -m "chore: initialize project with cc-forge"
  echo "  ✓ Git initialized"
fi

# ── Initialize Taskmaster ────────────────────────
echo ""
echo "▸ Initializing Taskmaster..."

if command -v task-master &> /dev/null; then
  task-master rules add claude 2>/dev/null || true
  task-master init 2>/dev/null || true
  echo "  ✓ Taskmaster initialized"
else
  echo "  ⚠ Taskmaster not installed — run hermes-install.sh first"
  echo "    Or manually: claude mcp add task-master-ai -- npx -y task-master-ai"
fi

# ── Done ─────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  HERMES INIT COMPLETE  ·  $PROJECT_NAME"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Created:"
echo "  ├── .cc-forge/state.json    (project state)"
echo "  ├── .claude/commands/       (hermes commands)"
echo "  ├── CLAUDE.md               (expand this)"
echo "  ├── PRD.md                  (fill this out first)"
echo "  ├── .env.example            (document your env vars)"
echo "  └── .github/workflows/      (doc sync + @claude)"
echo ""
echo "  Next steps:"
echo "  1. Open Claude Code:  claude"
echo "  2. Run onboarding:    /hermes-init"
echo "     (Hermes will interview you and complete the setup)"
echo ""
echo "  Or jump straight to writing your PRD:"
echo "  → Open PRD.md and describe what you're building"
echo "  → Then: /hermes gate review  (stage 02 SPEC)"
echo ""
